"""URDF generator for a rotary delta robot.

URDF only describes trees, but a delta robot is a closed chain.  The model used here
(also by the web URDF viewer, assets/js/delta/urdf.js — output must be identical):

  base_link ─ motor{i}_joint (revolute, ACTIVE) ─ upper_arm{i}
      upper_arm{i} ─ elbow{i}{a,b}_pitch ─ elbow{i}{a,b}_link ─ elbow{i}{a,b}_yaw ─ forearm{i}{a,b}
        (passive; the b rod mimics the a rod — parallelogram)
  base_link ─ effector_x ─ effector_y ─ effector_z (prismatic, VIRTUAL) ─ effector ─ tool_link ─ tcp

A joint-state publisher (ROS 2 driver / web viewer) computes every passive value from the
motor angles with forward kinematics, so the chain *looks* closed.

CLI:  python -m deltarobot.urdf --preset edu_dynamixel > delta.urdf
      python -m deltarobot.urdf --design my_design.json -o delta.urdf
"""

from __future__ import annotations

import argparse
import math
import sys
from typing import Dict, List, Sequence, Tuple

from . import kinematics as kin
from .design import DeltaDesign

HALF_PI = math.pi / 2
GRIPPER_STROKE = 0.006     # finger travel per side [m]; open = 0, closed = -GRIPPER_STROKE
GRIPPER_FINGER_X = 0.015   # finger offset from the tool axis when open [m]


def f(v: float) -> str:
    """Compact deterministic number format (mirrored in JS)."""
    s = "%.6f" % v
    s = s.rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _xyz(*v: float) -> str:
    return " ".join(f(x) for x in v)


def _inertial(mass: float, xyz: Tuple[float, float, float], ixx: float, iyy: float, izz: float) -> List[str]:
    return ['    <inertial>',
            '      <origin xyz="%s" rpy="0 0 0"/>' % _xyz(*xyz),
            '      <mass value="%s"/>' % f(mass),
            '      <inertia ixx="%s" ixy="0" ixz="0" iyy="%s" iyz="0" izz="%s"/>' % (f(ixx), f(iyy), f(izz)),
            '    </inertial>']


def _cyl(xyz: Tuple[float, float, float], rpy: Tuple[float, float, float], radius: float, length: float,
         material: str) -> List[str]:
    return ['    <visual>',
            '      <origin xyz="%s" rpy="%s"/>' % (_xyz(*xyz), _xyz(*rpy)),
            '      <geometry><cylinder radius="%s" length="%s"/></geometry>' % (f(radius), f(length)),
            '      <material name="%s"/>' % material,
            '    </visual>']


def _sphere(xyz: Tuple[float, float, float], radius: float, material: str) -> List[str]:
    return ['    <visual>',
            '      <origin xyz="%s" rpy="0 0 0"/>' % _xyz(*xyz),
            '      <geometry><sphere radius="%s"/></geometry>' % f(radius),
            '      <material name="%s"/>' % material,
            '    </visual>']


def _box(xyz: Tuple[float, float, float], size: Tuple[float, float, float], material: str) -> List[str]:
    return ['    <visual>',
            '      <origin xyz="%s" rpy="0 0 0"/>' % _xyz(*xyz),
            '      <geometry><box size="%s"/></geometry>' % _xyz(*size),
            '      <material name="%s"/>' % material,
            '    </visual>']


def _joint(name: str, kind: str, parent: str, child: str, xyz: Tuple[float, float, float],
           rpy: Tuple[float, float, float] = (0.0, 0.0, 0.0), axis: Sequence[float] = (),
           limit: Tuple[float, float, float, float] = (), mimic: str = "") -> List[str]:
    out = ['  <joint name="%s" type="%s">' % (name, kind),
           '    <parent link="%s"/>' % parent,
           '    <child link="%s"/>' % child,
           '    <origin xyz="%s" rpy="%s"/>' % (_xyz(*xyz), _xyz(*rpy))]
    if axis:
        out.append('    <axis xyz="%s"/>' % _xyz(*axis))
    if limit:
        out.append('    <limit lower="%s" upper="%s" effort="%s" velocity="%s"/>' % tuple(f(v) for v in limit))
    if mimic:
        out.append('    <mimic joint="%s" multiplier="1" offset="0"/>' % mimic)
    out.append('  </joint>')
    return out


def generate(design: DeltaDesign, name: str = "delta_robot") -> str:
    d = design
    R, r, L, l, w = d.base_radius, d.effector_radius, d.upper_arm, d.forearm, d.forearm_spacing
    tool = d.tool_spec
    tl = d.tool_length
    arm_r = max(0.006, 0.05 * L)
    rod_r = max(0.003, 0.012 * l)
    motor_r = min(0.05, max(0.014, 0.18 * R))
    motor_len = min(0.12, max(0.03, 0.35 * R))
    reach = R - r + L + l
    effort = float(d.motor_spec["peak_torque"]) * d.ratio * d.efficiency
    vel = float(d.motor_spec["max_speed"]) / d.ratio

    x: List[str] = ['<?xml version="1.0"?>',
                    '<!-- generated by deltarobot.urdf — R=%s r=%s L=%s l=%s w=%s motor=%s tool=%s -->'
                    % (f(R), f(r), f(L), f(l), f(w), d.motor, d.tool),
                    '<robot name="%s">' % name]
    for mat, rgba in (("frame", "0.55 0.6 0.68 1"), ("motor", "0.15 0.17 0.2 1"), ("arm", "0.9 0.55 0.15 1"),
                      ("rod", "0.12 0.12 0.14 1"), ("joint", "0.75 0.78 0.82 1"), ("plate", "0.25 0.55 0.9 1"),
                      ("tool", "0.2 0.75 0.5 1")):
        x.append('  <material name="%s"><color rgba="%s"/></material>' % (mat, rgba))

    # ---- base
    x.append('  <link name="base_link">')
    x += _cyl((0, 0, 0.02 + 0.006), (0, 0, 0), R + motor_r + 0.01, 0.012, "frame")
    for i in range(3):
        phi = kin.PHI[i]
        c, s = math.cos(phi), math.sin(phi)
        x += _cyl((R * c, R * s, 0), (HALF_PI, 0, phi), motor_r, motor_len, "motor")
    x += _inertial(3 * float(d.motor_spec["mass"]) + 0.5, (0, 0, 0.02), 0.01, 0.01, 0.02)
    x.append('  </link>')

    for i in range(3):
        n = i + 1
        phi = kin.PHI[i]
        c, s = math.cos(phi), math.sin(phi)
        x += _joint("motor%d_joint" % n, "revolute", "base_link", "upper_arm%d" % n,
                    (R * c, R * s, 0), (0, 0, phi), (0, 1, 0), (d.theta_min, d.theta_max, effort, vel))
        m = d.upper_arm_mass
        x.append('  <link name="upper_arm%d">' % n)
        x += _cyl((L / 2, 0, 0), (0, HALF_PI, 0), arm_r, L, "arm")
        x += _cyl((L, 0, 0), (HALF_PI, 0, 0), arm_r * 0.8, w + 2 * arm_r, "arm")
        x += _inertial(m + d.elbow_mass, (L / 2, 0, 0), 1e-5, m * L * L / 12, m * L * L / 12)
        x.append('  </link>')
        for k, sgn in (("a", 1.0), ("b", -1.0)):
            mimic_p = "" if k == "a" else "elbow%da_pitch" % n
            mimic_y = "" if k == "a" else "elbow%da_yaw" % n
            x += _joint("elbow%d%s_pitch" % (n, k), "revolute", "upper_arm%d" % n, "elbow%d%s_link" % (n, k),
                        (L, sgn * w / 2, 0), (0, 0, 0), (0, 1, 0), (-math.pi, math.pi, 0, 0), mimic_p)
            x.append('  <link name="elbow%d%s_link"/>' % (n, k))
            x += _joint("elbow%d%s_yaw" % (n, k), "revolute", "elbow%d%s_link" % (n, k), "forearm%d%s" % (n, k),
                        (0, 0, 0), (0, 0, 0), (0, 0, 1), (-HALF_PI, HALF_PI, 0, 0), mimic_y)
            mr = d.forearm_pair_mass / 2
            x.append('  <link name="forearm%d%s">' % (n, k))
            x += _cyl((l / 2, 0, 0), (0, HALF_PI, 0), rod_r, l, "rod")
            x += _sphere((0, 0, 0), rod_r * 1.8, "joint")
            x += _sphere((l, 0, 0), rod_r * 1.8, "joint")
            x += _inertial(mr, (l / 2, 0, 0), 1e-6, mr * l * l / 12, mr * l * l / 12)
            x.append('  </link>')

    # ---- virtual effector chain
    x += _joint("effector_x", "prismatic", "base_link", "effector_x_link", (0, 0, 0), (0, 0, 0), (1, 0, 0),
                (-reach, reach, 0, 0))
    x.append('  <link name="effector_x_link"/>')
    x += _joint("effector_y", "prismatic", "effector_x_link", "effector_y_link", (0, 0, 0), (0, 0, 0), (0, 1, 0),
                (-reach, reach, 0, 0))
    x.append('  <link name="effector_y_link"/>')
    x += _joint("effector_z", "prismatic", "effector_y_link", "effector", (0, 0, 0), (0, 0, 0), (0, 0, 1),
                (-(L + l), 0, 0, 0))
    x.append('  <link name="effector">')
    x += _cyl((0, 0, 0), (0, 0, 0), r + 0.012, 0.01, "plate")
    x += _inertial(d.effector_mass, (0, 0, 0), 1e-4, 1e-4, 2e-4)
    x.append('  </link>')
    x += _joint("tool_joint", "fixed", "effector", "tool_link", (0, 0, -0.005))
    x.append('  <link name="tool_link">')
    kind = tool["kind"]
    if kind == "suction":
        cup = max(0.01, math.sqrt(float(tool["force"]) / 60e3 / math.pi))
        x += _cyl((0, 0, -(tl - 0.008) / 2), (0, 0, 0), 0.006, tl - 0.008, "tool")
        x += _cyl((0, 0, -tl + 0.004), (0, 0, 0), cup, 0.008, "tool")
    elif kind == "gripper":
        x += _box((0, 0, -0.015), (0.06, 0.03, 0.03), "tool")      # fingers are child links (below)
    elif kind == "magnet":
        x += _cyl((0, 0, -tl / 2), (0, 0, 0), 0.0125, tl, "tool")
    else:
        x += _cyl((0, 0, -tl / 2), (0, 0, 0), 0.004, tl, "tool")
    x += _inertial(max(1e-3, float(tool["mass"])), (0, 0, -tl / 2), 1e-5, 1e-5, 1e-5)
    x.append('  </link>')
    if kind == "gripper":
        # parallel fingers: finger a slides along +x (negative = closing), finger b mirrors it
        grip = float(tool["force"])
        for k, sgn in (("a", 1.0), ("b", -1.0)):
            x += _joint("gripper_finger_%s" % k, "prismatic", "tool_link", "gripper_finger_%s_link" % k,
                        (sgn * GRIPPER_FINGER_X, 0, 0), (0, 0, 0), (sgn, 0, 0),
                        (-GRIPPER_STROKE, 0, grip, 0.05), "" if k == "a" else "gripper_finger_a")
            x.append('  <link name="gripper_finger_%s_link">' % k)
            x += _box((0, 0, -(tl + 0.03) / 2), (0.006, 0.02, tl - 0.03), "tool")
            x += _inertial(0.01, (0, 0, -(tl + 0.03) / 2), 1e-6, 1e-6, 1e-6)
            x.append('  </link>')
    x += _joint("tcp_joint", "fixed", "tool_link", "tcp", (0, 0, -tl + 0.005))
    x.append('  <link name="tcp"/>')
    x.append('</robot>')
    return "\n".join(x) + "\n"


ACTIVE = ["motor1_joint", "motor2_joint", "motor3_joint"]


def joint_state(design: DeltaDesign, theta: Sequence[float], tool: int = 0) -> Dict[str, float]:
    """All independent (non-mimic) joint values for the given motor angles (and tool state)."""
    p = kin.fk(design, theta)
    out: Dict[str, float] = {}
    for i in range(3):
        out["motor%d_joint" % (i + 1)] = float(theta[i])
    for i, (pitch, yaw) in enumerate(kin.passive_angles(design, theta, p)):
        # the rod pitch is measured from the upper arm, i.e. relative to theta
        out["elbow%da_pitch" % (i + 1)] = pitch
        out["elbow%da_yaw" % (i + 1)] = yaw
    out["effector_x"], out["effector_y"], out["effector_z"] = p
    if design.tool_spec["kind"] == "gripper":
        out["gripper_finger_a"] = -GRIPPER_STROKE if tool else 0.0
    return out


def main(argv: Sequence[str] = ()) -> int:
    ap = argparse.ArgumentParser(description="Generate a delta robot URDF")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--preset", default="edu_dynamixel")
    g.add_argument("--design", help="design JSON (from the web simulator 'export')")
    ap.add_argument("-o", "--output")
    ap.add_argument("--name", default="delta_robot")
    a = ap.parse_args(list(argv) or None)
    design = DeltaDesign.load(a.design) if a.design else DeltaDesign.preset(a.preset)
    text = generate(design, a.name)
    if a.output:
        with open(a.output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    else:
        # write UTF-8 bytes so redirection works on consoles without UTF-8 (cp949)
        out = getattr(sys.stdout, "buffer", None)
        if out is not None:
            out.write(text.encode("utf-8"))
            out.flush()
        else:
            sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
